services:
  backend:
    image: cozysnippet/simple-mocking-api:latest
    ports:
      - target: 8080
        published: 9090
        protocol: tcp
        mode: ingress
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - CORS_ALLOWED_ORIGINS=http://frontend.localhost,http://localhost:4000,http://localhost:4200
      - JAVA_OPTS=-Xmx512m -Xms256m
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/actuator/health || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 30s
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
        monitor: 30s
      rollback_config:
        parallelism: 1
        delay: 5s
        monitor: 20s
      resources:
        limits:
          memory: 768M
          cpus: "2.0"
        reservations:
          memory: 384M
          cpus: "1.0"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network:
    driver: overlay
    attachable: true