spring:
  application:
    name: simple_mocking_api

  # Server Configuration
  server:
    port: ${SERVER_PORT:8080}
    servlet:
      context-path: ${CONTEXT_PATH:/}

  # CORS Configuration
  web:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:80}
      allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
      allowed-headers: ${CORS_ALLOWED_HEADERS:*}
      allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}

# Application Configuration
app:
  # User Generation Settings
  user-generation:
    max-count: ${MAX_USER_GENERATION:100}
    default-count: ${DEFAULT_USER_GENERATION:10}

  # Mock Data Configuration
  mock-data:
    initial-users-count: ${INITIAL_USERS_COUNT:5}
    enable-initial-data: ${ENABLE_INITIAL_DATA:true}

# Logging Configuration
logging:
  level:
    com.cozysnippet.simple_mocking_api: ${LOG_LEVEL:INFO}
    org.springframework.web: ${WEB_LOG_LEVEL:WARN}
  pattern:
    console: "${CONSOLE_LOG_PATTERN:%d{yyyy-MM-dd HH:mm:ss} - %msg%n}"

# Management and Health Check
management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS:health,info}
  endpoint:
    health:
      show-details: ${HEALTH_SHOW_DETAILS:when-authorized}

